### PR TITLE
Catching 2 other common authentication errors

### LINKED ISSUE #78: Handle IdentityProviderException properly with guard
Example URL: `http://localhost:8000/oauth/connect/github?code=8b79dc6d93813956f275&state=53adf20aaed5b0614a5b46d3805887b7`

Here, this URL is a redirect from github, but the code already expired.

Currently, this is throwing a 500 error with the `GithubIdentityProviderException` -> `bad_verification_code` error.

You gave a great sample with `FacebookController` of how to handle that, but what about the security guard?

Here is mine (an abstract one):

```php
abstract class AbstractSocialAuthenticator extends SocialAuthenticator
{
    /**
     * @var RouterInterface
     */
    private $router;

    /**
     * @var TokenStorageInterface
     */
    private $tokenStorage;

    /**
     * @var FlashBagInterface
     */
    private $flashBag;

    /**
     * @var ClientRegistry
     */
    private $clientRegistry;

    /**
     * @var UserManager|UserManagerInterface
     */
    private $userManager;

    public function __construct(RouterInterface $router, TokenStorageInterface $tokenStorage, FlashBagInterface $flashBag, ClientRegistry $clientRegistry, UserManagerInterface $userManager)
    {
        Assert::isInstanceOf($userManager, UserManager::class);

        $this->router = $router;
        $this->tokenStorage = $tokenStorage;
        $this->flashBag = $flashBag;
        $this->clientRegistry = $clientRegistry;
        $this->userManager = $userManager;
    }

    /**
     * {@inheritdoc}
     */
    final public function start(Request $request, AuthenticationException $authException = null)
    {
        return new RedirectResponse($this->router->generate('login'));
    }

    /**
     * {@inheritdoc}
     */
    final public function supports(Request $request)
    {
        return $request->getPathInfo() === $this->router->generate($this->getSocialConnectRouteName());
    }

    /**
     * {@inheritdoc}
     */
    final public function getCredentials(Request $request)
    {
        return $this->fetchAccessToken($this->getOAuthClient());
    }

    /**
     * {@inheritdoc}
     */
    final public function getUser($credentials, UserProviderInterface $userProvider)
    {
        if (!$credentials instanceof AccessToken || !$userProvider instanceof UserProvider) {
            return null;
        }

        return $this->getUserByAccessToken($credentials, $userProvider);
    }

    final public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
    {
        $this->flashBag->add('error', $exception->getMessage());

        return new RedirectResponse($this->router->generate('homepage'));
    }

    final public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        return new RedirectResponse($this->getPreviousUrl($request, $providerKey));
    }

    final protected function getClientRegistry(): ClientRegistry
    {
        return $this->clientRegistry;
    }

    final protected function getUserManager(): UserManager
    {
        return $this->userManager;
    }

    final protected function getUserByPlatformIdAndEmail(string $platformField, int $platformId, string $email): UserInterface
    {
        // If an user is already logged in, we are on the account linking process.
        // Just return the connected user to update the information.
        if (null !== $this->tokenStorage->getToken()
            &&
            $this->tokenStorage->getToken()->getUser() instanceof UserInterface
        ) {
            return $this->tokenStorage->getToken()->getUser();
        }

        $user = $this->userManager->findUserBy([
            $platformField => $platformId,
        ]);

        if (null === $user) {
            $user = $this->userManager->findUserByEmail($email);
        }

        if (null === $user) {
            $user = $this->userManager->createUser()
                ->setUsername(\uniqid('u'))
                ->setPassword(\md5(\uniqid((string) \time())))
                ->setEnabled(true)
            ;
        }

        return $user;
    }

    abstract protected function getUserByAccessToken(AccessToken $accessToken, UserProvider $userProvider): User;

    abstract protected function getSocialConnectRouteName(): string;

    abstract protected function getOAuthClient(): OAuth2Client;
}
```

I call `fetchAccessToken` on `getCredentials` as suggested on https://github.com/knpuniversity/oauth2-client-bundle/issues/24#issuecomment-208993275, but this change nothing, the `onAuthenticationFailure` is never called.

Did I miss something?

### PR DESCRIPTION
**Pull request by weaverryan**
Fixes #78 

The entire point of `fetchAccessToken()` is to help catch as many "normal" errors as possible and turn them into proper "AuthenticationException" situations with decent messages.

### CODE REVIEW

File: src/Security/Exception/IdentityProviderAuthenticationException.php [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+
+    public function getMessageKey()
+    {
+        return 'Error fetching OAuth credentials: "%error%".';
+    }
+
+    public function getMessageData()
+    {
+        return [
+            'error' => $this->getPrevious()->getMessage(),
```
Comment (bocharsky-bw) [inline src/Security/Exception/IdentityProviderAuthenticationException.php]: I'm not sure, but don't we need to wrap the string with `%%` here like:
```php
return [
    '%error%' => $this->getPrevious()->getMessage(),
]
```
?

Comment (weaverryan) [reply src/Security/Exception/IdentityProviderAuthenticationException.php]: Oh man, you're TOTALLY right :)
